name: Deployment

on:
    workflow_dispatch:
      inputs:
        environment:
          description: 'The environment to deploy to (e.g. dev, test)'
          required: true

jobs:
  deployment-dev:
    runs-on: ubuntu-latest
    environment: dev
    if:  inputs.target-env == 'dev'
    steps:
        - name: checkout
          uses: actions/checkout@v3

        - name: deloyment to dev
          run: echo "My client1 is ${{ vars.CLIENT_1 }} "


  deployment-test:
    runs-on: ubuntu-latest
    environment: test
    if:  inputs.target-env == 'test'
    steps:
        - name: checkout
          uses: actions/checkout@v3

        - name: deloyment to test
          run: echo "My client1 is ${{ vars.CLIENT_1 }} "

