name: Deployment

on:
    workflow_dispatch:
      inputs:
        environment:
          description: 'The environment to deploy to (e.g. dev, test)'
          required: true

jobs:
  deployment:
    runs-on: ubuntu-latest
    #environment: dev
    steps:
        - name: checkout
          uses: actions/checkout@v3

        - name: deloyment
          run: echo "My client1 is ${{ vars.CLIENT_1 }} "