# This is a basic workflow to help you get started with Actions

name: Test CICD Workflow

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      PROJECT_NAME: ${{ vars.PROJECT_NAME }}
      PROJECT_CREATOR: ${{ vars.PROJECT_CREATOR }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      - name: Set version
        run: source set-version.sh

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo "App name: ${{ vars.APP_NAME}}, Project name: ${{ env.PROJECT_NAME }}, Project creator: ${{ env.PROJECT_CREATOR }}"
          echo test, and deploy your project.

      #- name: Build docker image and push
      #  uses: mr-smithers-excellent/docker-build-push@v6
      #  with:
      #    image: docker-hub-repo/test-cicd-imagename
      #    registry: docker.io
      #    username: ${{ secrets.DOCKER_HUB_USERNAME }}
      #    password: ${{ secrets.DOCKER_HUB_PASSWORD }}
    
